#!/bin/sh -eu

selfdir="$(dirname -- "$(realpath -- "$0")")"
path="$1"

module="pipestat.ko"

if insmod "$selfdir/$module" "path=$path" 2>&1 | grep -vi "resource busy"; then
    exit 1
fi

dmesg | grep -- "$path" | grep -- "${module%.ko}:" | tail -n1
